name: Unittests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install . 
    - name: Unzip data 
      run: |
        unzip data/ZTFBTS.zip
        unzip data/ZTFBTS_spectra.zip      
    - name: Run pytest
      run: |
        python -m pytest